# Generated by Django 4.1.3 on 2022-11-07 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('genre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_rental', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
