# Generated by Django 4.1.3 on 2022-11-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_delete_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_rental',
            new_name='date_added',
        ),
    ]
